language: node_js
sudo: true
node_js: '8'
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run build
  - npm run codecov
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_281ccd5189aa_key -iv $encrypted_281ccd5189aa_iv -in .env.enc -out .env -d || true'
env:
  global:
  - BX_APP=text-bot-openwhisk
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
before_deploy: npm install -g bx-blue-green
deploy:
  skip_cleanup: true
  provider: script
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/assistant-with-discovery-openwhisk
notifications:
  email: false
